# -*- coding: utf-8 -*-
"""Bundled story library — original retellings of classic Chinese folk tales
(all source tales are traditional/public-domain). Band 1: ages 4-7,
Band 2: ages 8-12, Band 3: ages 13-18."""

STORIES = [
    dict(
        id="xiaoma",
        title="小马过河",
        en="The Little Horse Crosses the River",
        band=1,
        color="river",
        moral="Try it yourself before you believe what others say.",
        text=[
            "小马和妈妈住在小河边。",
            "一天，妈妈说：“小马，请你把这袋麦子送到磨坊去吧。”",
            "小马来到河边，河水哗哗地流。",
            "小马问牛伯伯：“河水深吗？”",
            "牛伯伯说：“不深不深，才到我的小腿。”",
            "小马刚要过河，小松鼠大叫：“别过河！昨天我的朋友掉进了河里！”",
            "小马不知道怎么办，只好回家问妈妈。",
            "妈妈笑着说：“孩子，你自己试一试，就知道了。”",
            "小马小心地走进河里。",
            "河水不像牛伯伯说的那样浅，也不像松鼠说的那样深。",
            "小马开开心心地过了河。",
        ],
    ),
    dict(
        id="luobo",
        title="拔萝卜",
        en="The Enormous Turnip",
        band=1,
        color="garden",
        moral="Working together makes hard things easy.",
        text=[
            "老爷爷种了一个大萝卜。",
            "萝卜越长越大，大得不得了。",
            "老爷爷去拔萝卜。拔呀拔，拔不动。",
            "老爷爷叫老奶奶来帮忙。",
            "老奶奶拉着老爷爷，老爷爷拉着萝卜。拔呀拔，还是拔不动。",
            "小姑娘来了，小狗来了，小猫也来了。",
            "大家一个拉着一个，一起用力拔。",
            "“一、二、三！”大萝卜拔出来了！",
            "大家坐在地上，哈哈大笑。",
            "晚上，大家一起喝了香香的萝卜汤。",
        ],
    ),
    dict(
        id="kedou",
        title="小蝌蚪找妈妈",
        en="Little Tadpoles Look for Mama",
        band=1,
        color="pond",
        moral="Keep looking, keep asking — you will find your way.",
        text=[
            "池塘里有一群小蝌蚪，大大的脑袋，黑黑的身子，长长的尾巴。",
            "小蝌蚪想妈妈了，就去找妈妈。",
            "他们看见鸭妈妈，问：“您是我们的妈妈吗？”",
            "鸭妈妈说：“不是。你们的妈妈有四条腿，白白的肚子。”",
            "小蝌蚪看见一只大乌龟，大乌龟也有四条腿。",
            "“妈妈！妈妈！”小蝌蚪叫了起来。",
            "乌龟笑着说：“我不是你们的妈妈。你们的妈妈穿着绿衣服，会呱呱地唱歌。”",
            "小蝌蚪游呀游，看见一只大青蛙坐在荷叶上。",
            "“妈妈！我们找到你了！”",
            "青蛙妈妈说：“好孩子，你们长大了，快跳上来吧！”",
        ],
    ),
    dict(
        id="guitu",
        title="龟兔赛跑",
        en="The Tortoise and the Hare",
        band=1,
        color="meadow",
        moral="Slow and steady wins the race.",
        text=[
            "兔子跑得很快，乌龟爬得很慢。",
            "兔子对乌龟说：“我们来赛跑吧！”",
            "乌龟说：“好啊，我们比一比。”",
            "比赛开始了！兔子一下子跑得很远。",
            "兔子回头一看，乌龟还在后面慢慢地爬。",
            "“我先睡一觉吧。”兔子躺在大树下，睡着了。",
            "乌龟不停地爬，爬呀爬，爬过了大树。",
            "兔子醒来一看，乌龟已经到了终点！",
            "兔子红着脸说：“我不应该睡觉。”",
            "乌龟说：“只要不放弃，慢也能赢。”",
        ],
    ),
    dict(
        id="hudie",
        title="三只蝴蝶",
        en="Three Butterflies",
        band=1,
        color="flower",
        moral="Good friends stay together.",
        text=[
            "花园里有三只蝴蝶：一只红的，一只黄的，一只白的。",
            "他们天天一起玩，非常快乐。",
            "有一天，突然下起了大雨。",
            "三只蝴蝶飞到红花那里：“红花姐姐，让我们躲躲雨吧！”",
            "红花说：“红蝴蝶进来吧，别的不行。”",
            "红蝴蝶说：“我们是好朋友，要在一起！”",
            "他们又飞到黄花和白花那里，花儿都只让一只进去。",
            "三只蝴蝶说：“我们永远不分开！”",
            "太阳公公看见了，赶走了乌云。",
            "雨停了，三只蝴蝶又在花园里跳起舞来。",
        ],
    ),
    # ---- 变变一家 The Bianbian Family — original series for ages 4-7 ----
    dict(
        id="bb1",
        title="变变爸爸",
        en="Bianbian Family 1 · Meet Papa Bianbian",
        band=1,
        color="bianbian",
        moral="A loving papa can become anything you need.",
        text=[
            "变变爸爸是一个神奇的爸爸。",
            "他圆圆的，软软的，像一个大气球。",
            "他会变！他想变什么，就变什么。",
            "小鸟说：“我想飞。”变变爸爸就变成一架小飞机。",
            "圆圆说：“我想玩。”变变爸爸就变成一个大滑梯。",
            "方方说：“我困了。”变变爸爸就变成一张软软的床。",
            "大家都爱变变爸爸。",
            "你想让他变什么呢？",
        ],
    ),
    dict(
        id="bb2",
        title="小猫下不来了",
        en="Bianbian Family 2 · A Ladder for the Kitten",
        band=1,
        color="bianbian",
        moral="Helping others is a small thing that feels big.",
        text=[
            "小花猫爬到了大树上。",
            "树太高了，小花猫下不来，喵喵地哭。",
            "圆圆和方方着急地喊：“爸爸，快来呀！”",
            "变变爸爸跑过来，喊一声：“变！”",
            "他变成了一架长长的梯子，靠在大树上。",
            "小花猫顺着梯子，慢慢地爬了下来。",
            "“谢谢变变爸爸！”小花猫开心地叫。",
            "变变爸爸笑了：“不客气，这是小事一件！”",
        ],
    ),
    dict(
        id="bb3",
        title="下雨了",
        en="Bianbian Family 3 · Rain at the Picnic",
        band=1,
        color="bianbian",
        moral="Every rainy day hides a rainbow.",
        text=[
            "今天天气真好，变变一家去公园野餐。",
            "突然，乌云来了，哗啦啦，下起了大雨。",
            "“我的面包湿了！”方方大叫。",
            "变变爸爸喊一声：“变！”",
            "他变成了一把大大的伞，大家躲在下面。",
            "雨越下越大，地上的水变成了小河。",
            "变变爸爸又喊一声：“变！”",
            "他变成了一条小船，载着大家回家。",
            "雨停了，天上出现了一道彩虹。",
            "“今天真好玩！”圆圆和方方说。",
        ],
    ),
    dict(
        id="bb4",
        title="生日快乐",
        en="Bianbian Family 4 · The Best Birthday",
        band=1,
        color="bianbian",
        moral="The best present is time together.",
        text=[
            "今天是圆圆和方方的生日。",
            "变变爸爸说：“今天，你们想玩什么都可以！”",
            "“我要荡秋千！”变变爸爸就变成一个秋千。",
            "“我要坐小火车！”变变爸爸就变成一列小火车，呜呜地开。",
            "变变妈妈端来大蛋糕，上面有五根小蜡烛。",
            "大家一起唱生日歌，圆圆和方方吹灭了蜡烛。",
            "“爸爸，你真是世界上最好玩的爸爸！”",
            "变变爸爸变成一颗大大的爱心，抱住了大家。",
        ],
    ),
    dict(
        id="shouzhu",
        title="守株待兔",
        en="Waiting by the Stump for a Rabbit",
        band=2,
        color="field",
        moral="You cannot live on luck.",
        text=[
            "从前，宋国有一个农夫，他每天都在田里辛苦地干活。",
            "一天，一只兔子飞快地跑过来，一头撞在田边的树桩上，死了。",
            "农夫高兴极了：“今天真幸运，白白捡到一只兔子！”",
            "他把兔子带回家，美美地吃了一顿。",
            "从那天起，农夫再也不干活了。",
            "他天天坐在树桩旁边，等着兔子撞过来。",
            "可是，一天过去了，十天过去了，再也没有兔子来。",
            "田里长满了野草，庄稼全都枯死了。",
            "人们笑他说：“靠运气过日子，最后什么也得不到。”",
        ],
    ),
    dict(
        id="jingwa",
        title="井底之蛙",
        en="The Frog at the Bottom of the Well",
        band=2,
        color="well",
        moral="The world is bigger than what you can see.",
        text=[
            "一只青蛙住在一口浅井里。",
            "它对来喝水的小鸟说：“你看，我多快乐！我是这口井的主人。”",
            "“天空只有井口那么大，有什么好看的？”青蛙得意地说。",
            "小鸟笑了：“天空大得很，一眼望不到边。”",
            "青蛙不相信：“你骗人，天就是井口那么大。”",
            "小鸟说：“你跳出来看看就知道了。”",
            "青蛙鼓起勇气，跳出了井口。",
            "啊！外面有高山，有大海，有一望无际的天空。",
            "青蛙的脸红了：“原来世界这么大，是我见识太少了。”",
        ],
    ),
    dict(
        id="yugong",
        title="愚公移山",
        en="Yu Gong Moves the Mountains",
        band=2,
        color="mountain",
        moral="Persistence can move mountains.",
        text=[
            "从前，有两座大山，挡住了愚公家门前的路。",
            "愚公已经九十岁了，他对家人说：“我们一起把山移走吧！”",
            "第二天，全家人就开始挖山，把石头和泥土运到很远的海边。",
            "有个叫智叟的老人笑话他：“你这么老了，怎么可能移走大山？”",
            "愚公说：“我死了有儿子，儿子还有孙子，子子孙孙没有穷尽。”",
            "“可是山不会长高，挖一点就少一点，总有一天会挖平的。”",
            "智叟听了，说不出话来。",
            "天帝被愚公的坚持感动了，派神仙背走了两座大山。",
            "从此，愚公家门前变成了平坦的大路。",
        ],
    ),
    dict(
        id="houzi",
        title="猴子捞月",
        en="Monkeys Fish for the Moon",
        band=2,
        color="night",
        moral="Look up before you dive in.",
        text=[
            "晚上，一群猴子在山上玩。",
            "一只小猴子看见井里有个月亮，大叫起来：“不好了！月亮掉到井里了！”",
            "大猴子跑过来一看：“真的！我们快把月亮捞上来吧！”",
            "猴子们爬上井边的大树，一只接一只，倒挂下来，一直垂到井里。",
            "小猴子伸手去捞月亮，可是手一碰到水，月亮就碎了。",
            "等水面平静了，月亮又圆了，可就是捞不上来。",
            "老猴子抬头一看，笑了：“别捞了！月亮好好地挂在天上呢！”",
            "猴子们抬起头，看见了又大又圆的月亮。",
            "原来井里的只是月亮的影子啊。",
        ],
    ),
    dict(
        id="saiweng",
        title="塞翁失马",
        en="The Old Man Who Lost His Horse",
        band=3,
        color="steppe",
        moral="Fortune and misfortune trade places; judge slowly.",
        text=[
            "古时候，边塞住着一位老人，人们叫他塞翁。",
            "一天，塞翁家的马跑丢了，邻居们都来安慰他。",
            "塞翁却说：“丢了马，未必是坏事。”",
            "几个月后，那匹马回来了，还带回来一匹骏马。",
            "邻居们都来祝贺，塞翁却说：“白得一匹马，未必是好事。”",
            "塞翁的儿子喜欢骑马，有一天从马背上摔下来，摔断了腿。",
            "邻居们又来安慰，塞翁说：“腿断了，未必是坏事。”",
            "不久，战争爆发，村里的年轻人都被征去打仗，很多人再也没有回来。",
            "塞翁的儿子因为腿伤，留在了家里，保住了性命。",
            "福与祸常常互相转化，遇事不必过早下结论。",
        ],
    ),
    dict(
        id="kezhou",
        title="刻舟求剑",
        en="Marking the Boat to Find the Sword",
        band=3,
        color="boat",
        moral="Old methods fail in a changing world.",
        text=[
            "战国时候，楚国有个人坐船过江。",
            "船到江心，他一不小心，把心爱的宝剑掉进了江里。",
            "船上的人都替他着急：“快下水去捞吧！”",
            "那个人不慌不忙，掏出小刀，在船边刻了一个记号。",
            "他说：“我的剑是从这里掉下去的，等船靠岸，我从记号这里跳下去找。”",
            "船靠了岸，他从刻记号的地方跳进水里。",
            "可是捞了半天，什么也没有捞到。",
            "船一直在走，剑却沉在江底，怎么可能找得到呢？",
            "世界在变化，用老办法解决新问题，是行不通的。",
        ],
    ),
    dict(
        id="huashe",
        title="画蛇添足",
        en="Drawing Legs on a Snake",
        band=3,
        color="scroll",
        moral="Adding the unnecessary ruins the whole.",
        text=[
            "楚国有个人举行祭祀，赏给门客一壶酒。",
            "门客们商量：“一壶酒不够大家喝，不如比赛画蛇，谁先画好，酒就归谁。”",
            "有一个人画得最快，一转眼就画好了。",
            "他拿起酒壶，得意地看着别人，又提起笔来：“看，我还能给蛇添上几只脚！”",
            "他正画着蛇脚，另一个人也画好了。",
            "那人一把夺过酒壶，说：“蛇本来没有脚，你画的根本不是蛇！”",
            "说完，他把酒喝了。",
            "画蛇脚的人后悔极了，只好眼睁睁看着别人喝酒。",
            "做多余的事，不但没有好处，反而会坏事。",
        ],
    ),
]
